### PR TITLE
support passing login_hint to authorize

### PR DESCRIPTION
**Pull request by pushpabrol**

### CODE REVIEW

**Comment by obiwan007** [comment]
I Need this too. Please do the review 👍

**Comment by turbo** [comment]
@twistedstream Please take a look

**Comment by r4d1n** [comment]
Hello, thank you all for your work on this module. 

Do you intend to merge this PR? It would be useful to have this option available when using this strategy.

**Comment by Restuta** [comment]
Yes please!

**Comment by Restuta** [comment]
🎉 🎉 🎉  when is npm version bump? :) @machuga

**Pull request merged**
