### PR TITLE
Fix to not override option values with defaults.

### LINKED ISSUE #126: Options values being overwritten by defaults
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Providing URL values in the options should see those options used instead of being overwritten by defaults

### Reproduction

```javascript
const options = {
  domain: "foobar.com",
  authorizationURL: "http://foobar.com/authorize"
}

const strategy = new Strategy(options);

console.log(JSON.stringify(strategy.options));
```

This will see `authorizationURL` being set to the default of `https://foobar.com/authorize`.

This impacts my ability to stub out the authorisation server for testing purposes as the scheme is being force to HTTPS. It also negates the use of the Discovery endpoint if the config is hardcoded into the Strategy rather than being dynamic based on the data from the endpoint.

### Environment

> Please provide the following:

- **Version of this library used:** 1.3.3

### PR DESCRIPTION
**Pull request by kierans**
Also added extra test to check `options.apiUrl` had correct default assigned when missing.

By submitting a PR to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md). Please see the [contributing guidelines](https://github.com/auth0/.github/blob/master/CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo.

### Description

Fixes the strategy to not overwrite option values passed to the constructor with defaults.

### References

Fixes #126 

### Testing

`$ npm run test`

- [x] This change adds test coverage for new/changed/fixed functionality

### Checklist

- [x] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [x]  All active GitHub checks for tests, formatting, and security are passing
- [x] The correct base branch is being used, if not `master`

### CODE REVIEW

**Comment by kierans** [comment]
This isn't complete due to the handleIdTokenValidation function hardcoding the scheme/issuer.

**Comment by kierans** [comment]
This is now complete and needs to be reviewed by a reviewer so that it can be merged.

**Review by davidpatrick — CHANGES_REQUESTED** [review]
@kierans thanks for taking the time to raise a PR.  Allowing the user to override the `defaultOptions` is a welcomed change.  However changing the API to change building the `iss` from the `domain` to `expectedIssuer` would be a breaking change and doesn't enforce the `https` protocol.  Let's remove that from this PR and get the defaultOption overrides merged in.  Thanks 🙏

**Comment by kierans** [comment]
Thanks @davidpatrick for the feedback.

> However changing the API to change building the `iss` from the domain to `expectedIssuer` would be a breaking change

Could you please help me understand why this is considered a breaking change? Yes it extracts the building of the expected issuer into an overridable property however the default value remains the same. Therefore you could drop the change into an existing project with no change in behaviour, or changes required in client code. I see it as a completely backwards compatible change (albeit worthy of a minor patch bump).

> and doesn't enforce the https protocol.

You are correct in that it doesn't enforce the use of `https` because I could override the `expectedIssuer` to use `http`. However as stated [in the issue when I raised it](https://github.com/auth0/passport-auth0/issues/126) I want to use HTTP in a stubbed setup where the AS is completely under my control and colocated with the application for testing purposes (for example I have automated "controller tests" which test that authorisation guards are applied correctly to endpoints therefore I need a way to have my stub AS issue bearer tokens as required by the tests). In my opinion I should have that option to override the SDK's default behaviour because I'm willing to wear the risk.

**Comment by davidpatrick** [comment]
@kierans sorry about that I missed this line https://github.com/auth0/passport-auth0/pull/127/files#diff-6d186b954a58d5bb740f73d84fe39073R49 where you set the default expected issuer.

Actually everything looks good here 👍

**Review by davidpatrick — APPROVED** [review]

**Comment by kierans** [comment]
@davidpatrick Thanks for approving this change. Wondering how it can get merged/released please.

**Pull request merged**
